# Refer to https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-docker-with-devicemapper

- name: Ensure lvm2 is present
  yum:
    name: lvm2
    state: present

- name: Create volume group
  lvg:
    vg: "{{ docker_vg_name }}"
    pvs: "{{ docker_pvs }}"

- name: Create thinpool logical volume
  lvol:
    vg: "{{ docker_vg_name }}"
    lv: thinpool
    opts: "--wipesignatures y"
    size: "{{ docker_thinpool_size }}"

- name: Create thinpoolmeta logical volume
  lvol:
    vg: "{{ docker_vg_name }}"
    lv: thinpoolmeta
    opts: "--wipesignatures y"
    size: "{{ docker_thinpoolmeta_size }}"

- name: Convert to thin pool
  command: "lvconvert -y --zero n -c 512K --thinpool {{ docker_vg_name }}/thinpool --poolmetadata {{ docker_vg_name }}/thinpoolmeta"

- name: Set lvm profile
  template:
    src: templates/docker-thinpool.profile
    dest: "/etc/lvm/profile/{{ docker_vg_name }}-thinpool.profile"

- name: Apply lvm profile
  command: "lvchange --metadataprofile {{ docker_vg_name }}-thinpool {{ docker_vg_name }}/thinpool"
