- name: Copy Docker firewalld services to hosts
  copy:
    src: files/firewalld-services/
    dest: /etc/firewalld/services/
    owner: root
    group: root
    mode: 0440

- name: Docker remote API ports
  firewalld:
    service: docker-engine
    state: "{{ 'enabled' if enable_remote_api else 'disabled' }}"
    permanent: true

- name: Docker overlay networking ports
  firewalld:
    service: docker-overlay
    state: "{{ 'enabled' if enable_swarm_overlay_networks else 'disabled' }}"
    permanent: true

- name: Docker published ports
  firewalld:
    service: docker-publish
    state: "{{ 'enabled' if enable_swarm_service_ports else 'disabled' }}"
    permanent: true

- name: Docker swarm manager ports
  firewalld:
    service: docker-swarm
    state: "{{ 'enabled' if enable_swarm_manager_ports else 'disabled' }}"
    permanent: true

- name: Set masquerade on public zone
  firewalld:
    zone: public
    masquerade: yes
    state: enabled
    permanent: true
