- name: Copy Docker firewalld services to hosts
  copy:
    src: files/firewalld-services/
    dest: /etc/firewalld/services/
    owner: root
    group: root
    mode: 0440

- name: Docker remote API ports
  firewalld:
    service: docker-engine
    state: "{{ docker_remote_api }}"
    permanent: true

- name: Docker overlay networking ports
  firewalld:
    service: docker-overlay
    state: "{{ docker_overlay_networking }}"
    permanent: true

- name: Docker published ports
  firewalld:
    service: docker-publish
    state: "{{ docker_published_ports }}"
    permanent: true

- name: Docker swarm manager ports
  firewalld:
    service: docker-swarm
    state: "{{ docker_swarm_manager }}"
    permanent: true
